### ISSUE TITLE
Stack Pointer Address Invalid

### ISSUE THREAD

**Issue by fraser125** [tj90241/n64chain#9]
I'm having an issue where the sp register gets a starting value of 0x80000000 then when a function gets called it subtracts 0x8 from that and tries to write the value, this fires the TLB Exception Handler. I had this problem with the included HelloWorld running on Cen64 and MAME and Console. 
There might be other places or things going on but here is possibly a piece of the problem
https://github.com/tj90241/n64chain/blob/4c09848ab9a7e53099c278e953553bbb64d30a43/libn64/os/asm/syscall.s#L126
Thanks for any assistance.

**Comment by tj90241** [comment]
Trying increasing the memory size in `libn64_mm_init` in `libn64/os/main.c`.

In short, libn64 will only allocate from a pool of memory that you provide it. That default pool is something like 64kb.

I don't remember the examples not working - have you changed something?

**Comment by fraser125** [comment]
I'm on Windows 10

1. I cloned the git to a new folder.
2. Downloaded the latest n64chain from cen64.com and unzipped to the \tools folder
3. Placed header.bin in correct folder
4. Compiled the mkfs and checksum with gcc for Windows
5. Compiled libn64 with n64chain
6. Compiled libgfx with n64chain
7. Compiled helloworld with n64chain
No errors, just defined but not used warnings.

memory size is default: 
`libn64_mm_init(kernel_sp - 4096 * 16, kernel_sp);`

I don't think any of the following results are what you intended?
When I run on hardware I get nothing, Black Screen and PC monitor (w/S-Video) goes to sleep.

Is the character after "Hello, world" a Null or something else?
When I run it in Cen64 I get
![image](https://user-images.githubusercontent.com/1725115/43041849-652c7790-8d21-11e8-88e7-af7c4f693deb.png)
When I run it in MAME I get 
![image](https://user-images.githubusercontent.com/1725115/43041844-10302a0c-8d21-11e8-9896-61fe6d35b3ac.png)

I'm happy to work at debugging this, but the only debugger I've had good luck with is MAME which may not be accurate enough.

**Comment by tj90241** [comment]
Hmm, last time I tried it on hardware, I thought it worked fine. I'll have to try again soon.

The string probably is not NUL terminated, causing the corrupted characters.  You can do that here:
https://github.com/tj90241/n64chain/blob/master/helloworld/src/main.c#L62

Not sure why MAME crashes - looks like an emulator bug, though as you suspect...

A good way to start would be objdump the ELF and inspect address 0x80001070 to see what it is doing at that time.

**Comment by fraser125** [comment]
Sorry to take so long, I've been working on some other things. 
The problem isn't the size of the stack, it's definitely about the location.
![image](https://user-images.githubusercontent.com/1725115/43996813-021b7bdc-9d80-11e8-9f9b-89a3d3bcc3dc.png)
Here is what is at 8000'1070 so not what I would of expected. To be fair the crash screen shows after the 5th time the Bad Address Interrupt is fired. 
The first time it's triggered the EPC is 8000123C which makes more sense, because of the value in the sp register of the MAME capture.
![image](https://user-images.githubusercontent.com/1725115/43996829-77ab424c-9d80-11e8-97e3-4f3f86406d74.png)
				
Can you explain the stack location strategy? It's in a couple of different places.
In the Exception handler it's set to 0x80000400
https://github.com/tj90241/n64chain/blob/0bfcd345c4d8506c69478bae26ad6a7ccd455503/libn64/os/asm/exception.s#L270-L272
In the boot it's set to 0x807FE110.
https://github.com/tj90241/n64chain/blob/0bfcd345c4d8506c69478bae26ad6a7ccd455503/libn64/os/asm/boot.s#L42
Are these both expected? These make sense, especially if you are supporting recursive Exceptions.
What about this line in the syscall?
https://github.com/tj90241/n64chain/blob/0bfcd345c4d8506c69478bae26ad6a7ccd455503/libn64/os/asm/syscall.s#L126
Is it missing the lower 16 bits? Would it be for a new location or one of the existing locations?

The Hello World executes the boot.s which seems good, and then the syscall.s section that sets the sp register to 80000000 , this causes Memory Access Exception when a function is called because subtracting from 80000000 causes attempts to write to 7FFFFFF8 as the sp register shows in MAME capture above. The stack location code in exception.s hasn't been called up to this point.

**Comment by tj90241** [comment]
1. During boot, $SP gets set to ~0x807FE110, plus or minus depending on some static configuration.  This is a value just a bit below above the top of RDRAM -- 4 or 8MiB depending on whether or not an expansion pak is present. At this time, the TLB is not initialized (libn64 has barely switched from assembly to C yet), so that's why a somewhat-arbitrary physical address is used.

At the very top of RDRAM is a some preallocated memory for threads and the memory manager:
https://github.com/tj90241/n64chain/blob/master/libn64/os/main.c#L41

(0x8000_0000 = kseg0, 0x0080_0000 = 8MiB
>>> hex((0x80000000 | 0x800000) - 40*1024)
'0x807f6000'

2. Once the system is initialized, all threads are assigned a default $SP of 0x8000_0000.  The first time a word is pushed to the stack in that thread, it will be written to 0x7FFF_FFFC (or the very top of kuseg).  This will cause the TLB to step in and map the address to a physical location for the thread -- it is what gives libn64 the flexibility of dynamically allocated stacks.  If the TLB hasn't assigned a physical address for that thread/part of the stack yet, the exception handler at @ 0x8000_0000 is run.

3. $SP gets set to 0x80000180 when stuff hits the fan.  It is only assigned this value when the system is running in kernel mode and a fatal exception that will not be handled is raised.  At this time, we can't trust the TLB and we're not sure where we can get memory to render the exception screen -- so I picked some memory that I knew would be just enough to get the job done for this special case.

**Comment by tj90241** [comment]
I just dug around on the hardware...

For some reason, the PI interrupt is not getting caught (or the PI interrupt message is not getting into the main thread's queue) so it blocks indefinitely here:
https://github.com/tj90241/n64chain/blob/master/helloworld/src/main.c#L53

If you change that to `LIBN64_NOBLOCK`, it works as expected. Now to figure out why messages for PI interrupts aren't getting queued up on real hardware...

**Comment by fraser125** [comment]
I confirmed that with the LIBN64_NOBLOCK change it now looks just like cen64 on hardware. It seems like you understand the problem and are working on a long term fix, so I'll leave this issue open.
